### ISSUE TITLE
add URL to full issue in tweet

### ISSUE THREAD

**Issue by cneud** [shoutrlabs/berliner-schlagzeilen#2]
It would be nice to also include a link to the full newspaper issue in ZEFYS with each tweet.

**Comment by select** [comment]
Yes, this can be easily done now since the tweets are generated from the json file. 

But how much space does a URL take? The current URL scheme is quite long. 

http://zefys.staatsbibliothek-berlin.de/kalender/auswahl/date/1917-02-22/27971740/?no_cache=1

Would be nice to have a short link like

http://zefys.de/volkszeitung/1917-02-22

**Comment by select** [comment]
Ok to answer my own question :P

> Type or paste the URL into the Tweet box on twitter.com.
> A URL of any length will be altered to 23 characters, even if the link itself is less than 23 characters long. Your character count will reflect this.
> Click the Tweet button to post your Tweet and link.

**Comment by cneud** [comment]
Solved in https://github.com/shoutrlabs/berliner-schlagzeilen/commit/f3a9d67f5f68363a79e9c754f1340e73a6b55e95
